export const formInitialData = {
  role: "",
  account_type: "",
  registerlevel: "",
  mandi_state: "",
  apmcname: "",
  title: "",
  firstname: "",
  middlename: "",
  lastname: "",
  gender: "",
  dob: "",
  relation_type: "",
  relation_name: "",
  email: "",
  mobile: "",
  password: "",
  password_confirmation: "",
  address: "",
  state: "",
  district: "",
  taluka: "",
  village: "",
  collection_center:"",
  fpo_email:"",
  company_reg_no:"",
  organisation_name:"",
  organisation_address:"",
  organization_cni:"",
  org_pincode:"",
  fpo_state:"",
  fpo_district:"",
  fpo_city_village:"",
  establishment_date:"",
  bank_name:"",
  acc_holder_name:"",
  bank_acc_num:"",
  confirm_bank_acc_num:"",
  ifsc_code:"",
  confirm_ifsc_code:"",
  passbook_copy:"",
  pic:"",
  company_registration_certificate:""
}
